### ISSUE TITLE
Could not find class 'com.google.bitcoin.store.WalletProtobufSerializer'

### ISSUE THREAD

**Issue by saldisobi** [HashEngineering/dimecoin-wallet#3]
Could not find class 'com.google.bitcoin.store.WalletProtobufSerializer', referenced from method de.schildbach.wallet.WalletApplication.loadWalletFromProtobuf

Any idea where I am going wrong

**Comment by HashEngineering** [comment]
I have seen this problem before, but can't remember the cause at this time.

**Comment by HashEngineering** [comment]
This is probably because of a dependency issue.  The wallet pom.xml needs to match the dimecoinj pom.xml in terms of the name and version of the dimecoinj library.

**Comment by nsrajpoot** [comment]
dimecoinj is a java library that we build and specify path to in wallet 

dimecoinj pom

  <groupId>com.google</groupId>
  <artifactId>dimecoinj-parent</artifactId>
  <version>0.12-SNAPSHOT</version>
  <packaging>pom</packaging>

wallet pom.

<dependency>
            <groupId>com.google</groupId>
            <artifactId>dimecoinj</artifactId>
            <version>0.12-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>/home/saldi/Desktop/dimecoinj-0.12-SNAPSHOT.jar</systemPath>
        </dependency>

giving path of system

**Comment by nsrajpoot** [comment]
added compile path as well after installing jar on local repo

getting this error

02-07 12:26:37.209: E/AndroidRuntime(5906): FATAL EXCEPTION: main
02-07 12:26:37.209: E/AndroidRuntime(5906): java.lang.ExceptionInInitializerError
02-07 12:26:37.209: E/AndroidRuntime(5906):     at de.schildbach.wallet.WalletApplication.initLogging(WalletApplication.java:161)
02-07 12:26:37.209: E/AndroidRuntime(5906):     at de.schildbach.wallet.WalletApplication.onCreate(WalletApplication.java:102)
02-07 12:26:37.209: E/AndroidRuntime(5906):     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
02-07 12:26:37.209: E/AndroidRuntime(5906):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4290)
02-07 12:26:37.209: E/AndroidRuntime(5906):     at android.app.ActivityThread.access$1400(ActivityThread.java:143)
02-07 12:26:37.209: E/AndroidRuntime(5906):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1301)
02-07 12:26:37.209: E/AndroidRuntime(5906):     at android.os.Handler.dispatchMessage(Handler.java:99)
02-07 12:26:37.209: E/AndroidRuntime(5906):     at android.os.Looper.loop(Looper.java:137)
02-07 12:26:37.209: E/AndroidRuntime(5906):     at android.app.ActivityThread.main(ActivityThread.java:4960)
02-07 12:26:37.209: E/AndroidRuntime(5906):     at java.lang.reflect.Method.invokeNative(Native Method)
02-07 12:26:37.209: E/AndroidRuntime(5906):     at java.lang.reflect.Method.invoke(Method.java:511)
02-07 12:26:37.209: E/AndroidRuntime(5906):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)

**Comment by HashEngineering** [comment]
I built both dimecoinj and dimecoin-wallet without error, installed on my
phone and it runs without error.

Is there more to the crash log.  Usually there is a Caused By: section to
show where the error actually happened.  ExceptionInInitializerError
usually means that a member variable in WalletApplication is causing a
crash when it is assigned.

**Comment by nsrajpoot** [comment]
02-09 10:31:47.681: E/AndroidRuntime(24039): FATAL EXCEPTION: main
02-09 10:31:47.681: E/AndroidRuntime(24039): java.lang.NoClassDefFoundError: org.bitcoinj.wallet.Protos$Wallet
02-09 10:31:47.681: E/AndroidRuntime(24039):    at com.google.bitcoin.store.WalletProtobufSerializer.walletToProto(WalletProtobufSerializer.java:115)
02-09 10:31:47.681: E/AndroidRuntime(24039):    at com.google.bitcoin.store.WalletProtobufSerializer.writeWallet(WalletProtobufSerializer.java:94)
02-09 10:31:47.681: E/AndroidRuntime(24039):    at com.google.bitcoin.core.Wallet.saveToFileStream(Wallet.java:467)
02-09 10:31:47.681: E/AndroidRuntime(24039):    at com.google.bitcoin.core.Wallet.saveToFile(Wallet.java:302)
02-09 10:31:47.681: E/AndroidRuntime(24039):    at com.google.bitcoin.wallet.WalletFiles.saveNowInternal(WalletFiles.java:123)
02-09 10:31:47.681: E/AndroidRuntime(24039):    at com.google.bitcoin.wallet.WalletFiles.saveNow(WalletFiles.java:113)
02-09 10:31:47.681: E/AndroidRuntime(24039):    at com.google.bitcoin.core.Wallet.saveNow(Wallet.java:449)
02-09 10:31:47.681: E/AndroidRuntime(24039):    at com.google.bitcoin.core.Wallet.addKeys(Wallet.java:2027)
02-09 10:31:47.681: E/AndroidRuntime(24039):    at com.google.bitcoin.core.Wallet.addKey(Wallet.java:1997)
02-09 10:31:47.681: E/AndroidRuntime(24039):    at de.schildbach.wallet.WalletApplication.addNewKeyToWallet(WalletApplication.java:379)
02-09 10:31:47.681: E/AndroidRuntime(24039):    at de.schildbach.wallet.WalletApplication.ensureKey(WalletApplication.java:374)
02-09 10:31:47.681: E/AndroidRuntime(24039):    at de.schildbach.wallet.WalletApplication.onCreate(WalletApplication.java:156)
02-09 10:31:47.681: E/AndroidRuntime(24039):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)

**Comment by HashEngineering** [comment]
This dependency may be missing from the compile.  Just had this problem and that was the solution.
com.google.protobuf:protobuf-java:2.5.0
